In [1]:
#Task 1

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]
#a)
valid_transactions = []

for t in transactions:
    if t["price"] > 0 and t["quantity"] >=0:
        valid_transactions.append(t)

#b)
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

#c)
region_totals = {}

for t in valid_transactions:
    region = t["region"]

    if region not in region_totals:
        region_totals[region] = 0

    region_totals[region] += t["total"]

#d)
max_region = ""
max_value = 0

for region in region_totals:
    if region_totals[region] > max_value:
        max_value = region_totals[region]
        max_region = region

print(f"Region with highest revenue: {max_region} ({max_value})")

Region with highest revenue: EU (3600)


In [2]:
#Task 2

def summarise_sales(sales):

    # total
    total = sum(sales)

    # average
    average = round(total / len(sales), 2)

    # best day and worst day
    best_day = sales.index(max(sales)) + 1
    worst_day = sales.index(min(sales)) + 1

    # above average count
    count = 0
    for s in sales:
        if s > average:
            count +=1

    # return dictionary
    return {
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": count
    }

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

result = summarise_sales(sales)

print(result)

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


In [15]:
#Task 3

students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

#a)

passing = []

for student in students:
    if student["grade"] >=50:
        passing.append(student["name"])

print(passing)

#b)

for student in students:
    name = student["name"]
    grade = student["grade"]
    
    if grade >= 80:
        print(f"{name}: Excellent")
    elif grade >= 50:
        print(f"{name}: Pass")
    else:
        print(f"{name}: Fail")

#c)

count = 0

for student in students:
    if student["attendance"] < 0.80:
        count += 1

print(count)

#d)
top_student = None
top_grade = 0

for student in students:
    if student["grade"] > top_grade:
        top_grade = student["grade"]
        top_student = student["name"]

print(f"{top_student}: {top_grade}")

#e)

best = max(students, key=lambda x: x["grade"])

print(f"{best['name']}: {best['grade']}")

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass
4
Nina: 95
Nina: 95


In [26]:
#Task 4

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}
    
    # a) 
    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
            # update shares and price
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            # add new asset
            self.holdings[ticker] = {
                "shares": shares,
                "price_per_share": price_per_share
            }
    
    # b) 
    def total_value(self):
        total = 0
        for ticker in self.holdings:
            asset = self.holdings[ticker]
            total += asset["shares"] * asset["price_per_share"]
        return total
    
    # c) 
    def most_valuable(self):
        max_value = 0
        best_ticker = ""
        
        for ticker in self.holdings:
            asset = self.holdings[ticker]
            value = asset["shares"] * asset["price_per_share"]
            
            if value > max_value:
                max_value = value
                best_ticker = ticker
        
        return best_ticker
    
    # d) 
    def __str__(self):
        num_assets = len(self.holdings)
        total = self.total_value()
        
        return f"Owner: {self.owner}, Assets: {num_assets}, Total Value: {total}"

portfolio = Portfolio("Kevin")

portfolio.add_asset("AAPL", 10, 150)
portfolio.add_asset("GOOG", 5, 1000)
portfolio.add_asset("TSLA", 8, 200)

print(portfolio.total_value())
print(portfolio.most_valuable())
print(portfolio)

8100
GOOG
Owner: Kevin, Assets: 3, Total Value: 8100


In [16]:
#Task 5
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]
from datetime import datetime

dates = []

for order in orders:
    date_string = order[0]
    date_object = datetime.strptime(date_string, "%Y-%m-%d").date()
    dates.append(date_object)

earliest = min(dates)
latest = max(dates)

difference = (latest - earliest).days

print(difference)

80


In [7]:
#Task 6

import numpy as np

#a)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]
])
row_sums = revenue.sum(axis=1)
print(row_sums)

#b)
col_means = revenue.mean(axis=0)
print(col_means)

#c)
growth = np.array([1.05, 1.03, 1.08, 1.02])

adjusted_2024 = revenue[2] * growth

print(adjusted_2024)

#d)
high_values = revenue[revenue > 250]

print(high_values)

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[262.5 298.7 248.4 316.2]
[260 270 290 310]


In [8]:
#Task 7

import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)
print(df)

#a)
df["salary_per_year_exp"] = (df["salary"] / df["years_exp"]).round()

print(df)

#b)
top3 = df.sort_values(by="performance_score", ascending=False).head(3)

print(top3)

#c)
finance_high = df.loc[
    (df["department"] == "Finance") & (df["performance_score"] > 4.0)
]

print(finance_high)

#d)
df = df.rename(columns={"years_exp": "experience_years"})

print(df)

#e)
result = df.iloc[:4, [2, 4]]

print(result)

  employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
1     Erik  Marketing    4000          3                3.8   
2      Mia    Finance    4800          7                4.5   
3      Leo         IT    5200         10                4.0   
4     Sara  Marketing    3900          2                3.5   
5      Tom         IT    5100          8                4.9   

   salary_per_year_exp  
0                900.0  
1               1333.0  
2                686.0  
3                520.0  
4            

In [23]:
#Task 8

import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

#a)
df = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

df = df.set_index("date")

print(df.head())

#b)
df["conversions"] = (df["visitors"] * df["conversion_rate"]).round()

df["daily_revenue"] = df["conversions"] * df["avg_order_value"]

print(df.head())

            visitors  conversion_rate  avg_order_value
date                                                  
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39
            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   

            daily_revenue  
date                       
2025-01-06         835.90  
2025-01-07        1307.88  
2025-